name: Rust

on:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.95.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - name: Build Workspace
        run: cargo build --workspace

      - name: Build Tests
        run: cargo build --tests --workspace

  check:
    name: Check (Clippy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUST_LOG: trace,tokio_postgres=info
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Run Tests
        run: cargo test

      - name: Run Tests with metrics
        run: cargo test -F metrics
